# house price prediction using machine learning project

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mumbai.csv')
df

Price  Area        Location  ...  Sofa  Wardrobe  Refrigerator
0      4850000   720        Kharghar  ...     0         0             0
1      4500000   600        Kharghar  ...     0         0             0
2      6700000   650        Kharghar  ...     0         0             0
3      4500000   650        Kharghar  ...     0         1             0
4      5000000   665        Kharghar  ...     0         0             0
...        ...   ...             ...  ...   ...       ...           ...
7714  14500000  1180  Mira Road East  ...     9         9             9
7715  14500000   530    Naigaon East  ...     9         9             9
7716   4100000   700        Shirgaon  ...     9         9             9
7717   2750000   995  Mira Road East  ...     9         9             9
7718   2750000  1020  Mira Road East  ...     9         9             9

[7719 rows x 40 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head()

Price  Area  Location  ...  Sofa  Wardrobe  Refrigerator
0  4850000   720  Kharghar  ...     0         0             0
1  4500000   600  Kharghar  ...     0         0             0
2  6700000   650  Kharghar  ...     0         0             0
3  4500000   650  Kharghar  ...     0         1             0
4  5000000   665  Kharghar  ...     0         0             0

[5 rows x 40 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7719 entries, 0 to 7718
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Price                7719 non-null   int64 
 1   Area                 7719 non-null   int64 
 2   Location             7719 non-null   object
 3   No. of Bedrooms      7719 non-null   int64 
 4   Resale               7719 non-null   int64 
 5   MaintenanceStaff     7719 non-null   int64 
 6   Gymnasium            7719 non-null   int64 
 7   SwimmingPool         7719 non-null   int64 
 8   LandscapedGardens    7719 non-null   int64 
 9   JoggingTrack         7719 non-null   int64 
 10  RainWaterHarvesting  7719 non-null   int64 
 11  IndoorGames          7719 non-null   int64 
 12  ShoppingMall         7719 non-null   int64 
 13  Intercom             7719 non-null   int64 
 14  SportsFacility       7719 non-null   int64 
 15  ATM                  7719 non-null   int64 
 16  ClubHo

In [ ]:
df.duplicated().sum()

794

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.replace(9, np.nan, inplace=True)
df = df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1156 entries, 0 to 1397
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Price                1156 non-null   int64  
 1   Area                 1156 non-null   int64  
 2   Location             1156 non-null   object 
 3   No. of Bedrooms      1156 non-null   int64  
 4   Resale               1156 non-null   int64  
 5   MaintenanceStaff     1156 non-null   float64
 6   Gymnasium            1156 non-null   float64
 7   SwimmingPool         1156 non-null   float64
 8   LandscapedGardens    1156 non-null   float64
 9   JoggingTrack         1156 non-null   float64
 10  RainWaterHarvesting  1156 non-null   float64
 11  IndoorGames          1156 non-null   float64
 12  ShoppingMall         1156 non-null   float64
 13  Intercom             1156 non-null   float64
 14  SportsFacility       1156 non-null   float64
 15  ATM                  1156 non-null   f

In [ ]:
x= df.iloc[:,1:].values
x

array([[720, 'Kharghar', 1, ..., 0.0, 0.0, 0.0],
       [600, 'Kharghar', 1, ..., 0.0, 0.0, 0.0],
       [650, 'Kharghar', 1, ..., 0.0, 0.0, 0.0],
       ...,
       [1267, 'Belapur', 3, ..., 0.0, 0.0, 0.0],
       [1245, 'Airoli', 2, ..., 0.0, 0.0, 0.0],
       [1183, 'Airoli', 2, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
y=df.iloc[:,0:1].values
y

array([[ 4850000],
       [ 4500000],
       [ 6700000],
       ...,
       [19000000],
       [14900000],
       [14000000]])

In [ ]:
print(x[:, 1])

['Kharghar' 'Kharghar' 'Kharghar' ... 'Belapur' 'Airoli' 'Airoli']


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 1] = le.fit_transform(x[:, 1])
print(x[:, 1])

[80 80 80 ... 17 2 2]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size=0.3, random_state = 20)
x_train


array([[1267, 220, 3, ..., 0.0, 1.0, 0.0],
       [685, 196, 1, ..., 0.0, 0.0, 0.0],
       [600, 80, 1, ..., 0.0, 0.0, 0.0],
       ...,
       [1150, 80, 2, ..., 0.0, 0.0, 0.0],
       [1320, 126, 2, ..., 0.0, 0.0, 0.0],
       [1135, 209, 2, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = regressor.predict(x_test)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
mse = mean_squared_error(y_test, y_pred)
mse

132149497867685.58

In [ ]:
mae= mean_absolute_error(y_test, y_pred)
mae

7911931.374290465

In [ ]:
rs = r2_score(y_test, y_pred)
rs

0.49428647325006525